name: Check Ruby version

on:
  push:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check Ruby version
        uses: actions/checkout@v3
      -  run: |
          git fetch --tags && \
          this_version=$(cat nutek-apple.rb | grep \$this_version | awk '{print $3}' | sed 's/"//g' | head -n 1) && \
          latest_tag=$(git describe --tags --abbrev=0 --always) && \
          if [[ $this_version != $latest_tag ]]; then \
            echo "The Ruby version in nutek-apple.rb - $this_version - does not match the latest tag - $latest_tag" && \
            exit 1 ; \
          fi 
